baseurl = "https://trepidacious.github.io/"
languageCode = "en-us"
title = "trepidacious.github.io"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "trepidacious"
	description = "Notes and docs for trepidacious' github projects."
	copyright = "Released under the MIT license"

	# Repository
	# provider = "GitHub"
	# repo_url = "https://github.com/trepidacious/gh-pages-hugo"

	# version = "1.0.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = [
		"css/code.css"
	]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

[params.palette]
	primary = "deep-purple"
	accent  = "deep-orange"

[params.font]
	text = "Roboto"
	code = "Roboto Mono"

[social]
	twitter = ""
	github  = "trepidacious"
	email   = "trepidacious@gmail.com"

[[menu.main]]
	name   = "Material"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "React"
	url    = "react/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

[[menu.main]]
	name   = "Roadmap"
	url    = "roadmap/"
	weight = 30

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
